pjm_app_actus_index:
    path:     /{page}
    methods: [ get ]
    defaults: { _controller: PJMAppBundle:Actus:index, page: 1 }
    requirements:
        page:  \d*

pjm_app_actus_extrait:
    path:     /extrait/{nombre}
    methods: [ get ]
    defaults: { _controller: PJMAppBundle:Actus:extrait, nombre: 4 }
    requirements:
        nombre:  \d*

pjm_app_actus_voir:
    path:      /article/{slug}
    methods: [ get ]
    defaults:  { _controller: PJMAppBundle:Actus:voir }

pjm_app_actus_ajouter:
    path:      /ajouter
    methods: [ get, post ]
    defaults:  { _controller: PJMAppBundle:Actus:ajouter }

pjm_app_actus_modifier:
    path:      /modifier/{slug}
    methods: [ get, post ]
    defaults:  { _controller: PJMAppBundle:Actus:modifier }

pjm_app_actus_supprimer:
    path:      /supprimer/{slug}
    methods: [ get, post ]
    defaults:  { _controller: PJMAppBundle:Actus:supprimer }
