pjm_app_consos_brags_admin_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Brags:admin }

pjm_app_consos_brags_admin_listeCommandes:
    path:     /listeCommandes
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeCommandes }

pjm_app_consos_brags_admin_validerCommande:
    path:     /valider/{commande}
    defaults: { _controller: PJMAppBundle:Consos/Brags:validerCommande }

pjm_app_consos_brags_admin_resilierCommande:
    path:     /resilier/{commande}
    defaults: { _controller: PJMAppBundle:Consos/Brags:resilierCommande }

pjm_app_consos_brags_admin_listeBucquages:
    path:     /listeBucquages
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeBucquages }

pjm_app_consos_brags_admin_listeCredits:
    path:     /listeCredits
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeCredits }

pjm_app_consos_brags_admin_listeVacances:
    path:     /listeVacances
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeVacances }

pjm_app_consos_brags_admin_annulerVacances:
    path:     /annulerVacances/{vacances}
    defaults: { _controller: PJMAppBundle:Consos/Brags:annulerVacances }

pjm_app_consos_brags_admin_listePrix:
    path:     /listePrix
    defaults: { _controller: PJMAppBundle:Consos/Brags:listePrix }

pjm_app_consos_brags_admin_listeZiBrags:
    path:     /listeZiBrags
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeZiBrags }

pjm_app_consos_brags_admin_removeZiBrags:
    path:     /removeZiBrags/{user}
    defaults: { _controller: PJMAppBundle:Consos/Brags:removeZiBrags }

pjm_app_consos_brags_bucquage:
    path:     /bucquage
    defaults: { _controller: PJMAppBundle:Consos/Brags:bucquageCron }
