pjm_app_consos_brags_admin_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Brags:admin }

pjm_app_consos_brags_admin_listeCommandes:
    path:     /listeCommandes
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeCommandes }

pjm_app_consos_brags_admin_validerCommande:
    path:     /valider/{commande}
    defaults: { _controller: PJMAppBundle:Consos/Brags:validerCommande }

pjm_app_consos_brags_admin_listeBucquages:
    path:     /listeBucquages
    defaults: { _controller: PJMAppBundle:Consos/Brags:listeBucquages }

pjm_app_consos_brags_admin_listePrix:
    path:     /listePrix
    defaults: { _controller: PJMAppBundle:Consos/Brags:listePrix }
