pjm_app_consos_historique:
    path:     /historique
    defaults: { _controller: PJMAppBundle:Consos:historique }

pjm_app_consos_historiqueResults:
    path:     /historique/results
    defaults: { _controller: PJMAppBundle:Consos:historiqueResults }

pjm_app_consos_voirResponsables:
    path:     /{slug}/responsables
    defaults: { _controller: PJMAppBundle:Consos/Boquette:voirResponsables }

pjm_app_consos_boquette_historique:
    path:     /{slug}/historique
    defaults: { _controller: PJMAppBundle:Consos/Boquette:historique }

pjm_app_consos_rechargement:
    path:     /{slug}/rechargement
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement }

pjm_app_consos_pians:
    resource: "@PJMAppBundle/Resources/config/Consos/Pians/routing.yml"
    prefix:   /pians

pjm_app_consos_cvis:
    resource: "@PJMAppBundle/Resources/config/Consos/Cvis/routing.yml"
    prefix:   /cvis

pjm_app_consos_brags:
    resource: "@PJMAppBundle/Resources/config/Consos/Brags/routing.yml"
    prefix:   /brags

pjm_app_consos_paniers:
    resource: "@PJMAppBundle/Resources/config/Consos/Paniers/routing.yml"
    prefix:   /paniers
