pjm_app_consos_pians:
    path:     /pians
    defaults: { _controller: PJMAppBundle:Consos/Pians:index }

pjm_app_consos_brags:
    path:     /brags
    defaults: { _controller: PJMAppBundle:Consos/Brags:index }

pjm_app_consos_rechargement_getURL:
    path:     /rechargement
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:getURL }
