pjm_app_consos_pians:
    path:     /pians
    defaults: { _controller: PJMAppBundle:Consos/Pians:index }

pjm_app_consos_brags:
    resource: "@PJMAppBundle/Resources/config/Consos/Brags/routing.yml"
    prefix:   /brags
