pjm_app_lydia_rechargement_getURL:
    path:     /envoi/{transaction}
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:getURL }

pjm_app_lydia_rechargement_confirm:
    path:     /confirm
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:confirm }

pjm_app_lydia_rechargement_cancel:
    path:     /cancel
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:cancel }

pjm_app_lydia_rechargement_expire:
    path:     /expire
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:expire }

pjm_app_lydia_rechargement_success:
    path:     /success
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:success }

pjm_app_lydia_rechargement_fail:
    path:     /fail
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:fail }