parameters:
#    pjm_user.example.class: PJM\UserBundle\Example

services:
#    pjm_user.example:
#        class: %pjm_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
