parameters:
#    pjm_user.example.class: PJM\UserBundle\Example

services:
    pjm_user.registration.form.type:
        class: PJM\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pjm_user_registration }
    activity_listener:
        class: PJM\UserBundle\Listener\ActivityListener
        arguments: [@security.token_storage, @doctrine.orm.default_entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
