pjm_app_admin_consos_paniers_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Paniers:admin }

pjm_app_admin_consos_paniers_listePaniers:
    path:     /gestionPaniers
    defaults: { _controller: PJMAppBundle:Consos/Paniers:gestionPaniers }

pjm_app_admin_consos_paniers_paniersResults:
    path:     /listePaniers/results
    defaults: { _controller: PJMAppBundle:Consos/Paniers:paniersResultsAdmin }

pjm_app_admin_consos_paniers_voirCommandes:
    path:     /voirCommandes/{panier}
    defaults: { _controller: PJMAppBundle:Consos/Paniers:voirCommandes }
    options:
        expose: true
