pjm_app_admin_consos_gestionCredits:
    path:     /{slug}/gestionCredits
    defaults: { _controller: PJMAppBundle:Consos/Boquette:gestionCredits }

pjm_app_admin_consos_creditsResults:
    path:     /{boquette_slug}/gestionCredits/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:creditsResults }

pjm_app_admin_consos_pians:
    resource: "@PJMAppBundle/Resources/config/Admin/Consos/Pians/routing.yml"
    prefix:   /pians

pjm_app_admin_consos_brags:
    resource: "@PJMAppBundle/Resources/config/Admin/Consos/Brags/routing.yml"
    prefix:   /brags

pjm_app_admin_consos_paniers:
    resource: "@PJMAppBundle/Resources/config/Admin/Consos/Paniers/routing.yml"
    prefix:   /paniers

pjm_app_admin_consos_cvis:
    resource: "@PJMAppBundle/Resources/config/Admin/Consos/Cvis/routing.yml"
    prefix:   /cvis
