imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level:       error
            handler:            grouped
        grouped:
            type:               group
            members:            [streamed, swift]
        streamed:
            type:               stream
            path:               "%kernel.logs_dir%/%kernel.environment%.log"
            level:              debug
        swift:
            type:               swift_mailer
            from_email:         error@physbook.fr
            to_email:           error@physbook.fr
            subject:            "[Phy'sbook] Oops"
            level:              error
        login:
            type:               stream
            path:               "%kernel.logs_dir%/auth.log"
            level:              error
            channels:           security
        console:
            type:   console
            path:   "%kernel.logs_dir%/console.log"
