imports:
    - { resource: security.yml }
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:
        fallback: "%locale%"
        logging: false
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: v1r20151219
        packages:
            js:
                version: v1r20160105
            css:
                version: v1r20160105
            sw:
                version: v1r20160311
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: physbook_session
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'
            - 'LexikFormFilterBundle:Form:form_div_layout.html.twig'
            - 'PJMAppBundle:Form:datetimepicker_layout.html.twig'
            - 'PJMAppBundle:Form:select2_layout.html.twig'
            - 'PJMAppBundle:Form:helpers.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "FOSCommentBundle" ]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        platform_service: doctrine_dbal_platform
        mapping_types:
            enum:       string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            numeric_functions:
                regexp: PJM\AppBundle\DoctrineFunctions\RegexpFunction
                month: PJM\AppBundle\DoctrineFunctions\Month
                day: PJM\AppBundle\DoctrineFunctions\Day

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    encryption: %mailer_encryption%
    port:       %mailer_port%
    spool:     { type: memory }

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

genemu_form:
    select2: ~

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    PJM\AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        zi@physbook.fr
        sender_name:    Phy'sbook
    registration:
        form:
            type: pjm_user_registration
    resetting:
        email:
            template: PJMAppBundle:Mail:resetting.html.twig

kms_froala_editor:
    language: "fr"
    imageUpload:
        folder: /uploads/froala
    includeJQuery: false
    inlineMode: false
    plugins:
        mediaManager: true

fos_comment:
    db_driver: orm
    class:
        model:
            comment: PJM\AppBundle\Entity\Commentaires\Comment
            thread: PJM\AppBundle\Entity\Commentaires\Thread
            vote: PJM\AppBundle\Entity\Commentaires\Vote
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ASSO_COM
        thread:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

lexik_form_filter:
    where_method: and

minishlink_web_push:
  api_keys:
    GCM: %android_gcm_api_key%

sg_datatables:
  query:
    search_on_non_visible_columns: true
