security:
    encoders:
        PJM\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_MODERATEUR:  [ROLE_USER]
        ROLE_AUTEUR:      [ROLE_USER]
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        main:
            pattern: ^/
            provider:  fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key: %secret%
            anonymous: true



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/news/, roles: ROLE_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
