security:
    encoders:
        PJM\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_EXT:             [ROLE_USER]

        ROLE_ZIBRAGS:         [ROLE_USER, ROLE_HARPAGS]
        ROLE_ZICVIS:          [ROLE_USER]
        ROLE_ZIPIANS:         [ROLE_USER]
        ROLE_ZIPANIERS:       [ROLE_USER, ROLE_HARPAGS]
        ROLE_ZI:              [ROLE_ZIBRAGS, ROLE_ZICVIS, ROLE_ZIPIANS, ROLE_ZIPANIERS]

        ROLE_HARPAGS:         [ROLE_USER]
        ROLE_ZIPIANS_HARPAGS: [ROLE_ZIPIANS, ROLE_HARPAGS]
        ROLE_LISTE_HARPAGS:   [ROLE_ZICVIS_HARPAGS, ROLE_ZIPIANS_HARPAGS]

        ROLE_ASSO:            [ROLE_USER]
        ROLE_ASSO_COM:        [ROLE_ASSO]
        ROLE_ASSO_ZI:         [ROLE_ZI, ROLE_ASSO]
        ROLE_ASSO_TRESORS:    [ROLE_ZI, ROLE_ASSO, ROLE_LISTE_HARPAGS]

        ROLE_LISTE_ASSO:      [ROLE_ASSO_ZI, ROLE_ASSO_COM, ROLE_ASSO_TRESORS]

        ROLE_ADMIN:           [ROLE_LISTE_ASSO, ROLE_EXT]
        ROLE_SUPER_ADMIN:     [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        main:
            pattern: ^/
            provider:  fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key: %secret%
            anonymous: true



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/smoney/retour, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/boquette/brags/, roles: ROLE_ZIBRAGS }
        - { path: ^/admin/boquette/cvis/, roles: ROLE_ZICVIS }
        - { path: ^/admin/boquette/pians/, roles: ROLE_ZIPIANS }
        - { path: ^/admin/boquette/paniers/, roles: ROLE_ZIPANIERS }
        - { path: ^/admin/boquette/asso/, roles: ROLE_ASSO }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
