services:
  pjm.datatable.achats:
    class: PJM\AppBundle\Datatables\AchatsDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.transferts:
    class: PJM\AppBundle\Datatables\TransfertsDatatable
    calls:
        - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
        - { name: sg.datatable.view }
  pjm.datatable.vacances:
    class: PJM\AppBundle\Datatables\VacancesDatatable
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.prix:
    class: PJM\AppBundle\Datatables\PrixDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.commandes:
    class: PJM\AppBundle\Datatables\CommandesDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.credits:
    class: PJM\AppBundle\Datatables\CreditsDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.boquette.historique:
    class: PJM\AppBundle\Datatables\HistoriqueBoquetteDatatable
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.paniers.liste:
    class: PJM\AppBundle\Datatables\Admin\PaniersDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.responsabilites:
    class: PJM\AppBundle\Datatables\ResponsabilitesDatatable
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.boquettes:
    class: PJM\AppBundle\Datatables\Admin\BoquettesDatatable
    calls:
      - [setImageExt, ["@pjm.services.image"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.responsable:
    class: PJM\AppBundle\Datatables\ResponsableDatatable
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.consos.comptes:
    class: PJM\AppBundle\Datatables\Admin\ComptesDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.boquette.item:
    class: PJM\AppBundle\Datatables\Boquette\ItemDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
      - [setImageExt, ["@pjm.services.image"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.featuredItem:
    class: PJM\AppBundle\Datatables\Admin\FeaturedItemDatatable
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.admin.media.photos:
    class: PJM\AppBundle\Datatables\Admin\Media\PhotoDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
      - [setImageExt, ["@pjm.services.image"]]
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.pushsubscription:
    class: PJM\AppBundle\Datatables\PushSubscriptionDatatable
    tags:
      - { name: sg.datatable.view }
  pjm.datatable.annuaire:
    class: PJM\AppBundle\Datatables\AnnuaireDatatable
    calls:
      - [setIntranetExt, ["@pjm.twig.intranet_extension"]]
    tags:
      - { name: sg.datatable.view }
