services:
  pjm.form.type.userFileParser:
    class: PJM\AppBundle\Form\Type\Parser\UserFileParserType
    arguments: ["@pjm.services.user_manager", "@pjm.services.file_manager", "@pjm.services.excel"]
    tags:
      - { name: form.type, alias: userFileParser }
  pjm.form.type.datetimePicker:
    class: PJM\AppBundle\Form\Type\DateTimePickerType
    tags:
      - { name: form.type, alias: datetimePicker }
  pjm.form.extension.helpLabel:
    class: PJM\AppBundle\Form\Extension\HelpLabelExtension
    tags:
      - { name: form.type_extension, alias: form }
  pjm.form.extension.select2tags:
    class: PJM\AppBundle\Form\Extension\Select2TagsExtension
    tags:
      - { name: form.type_extension, alias: genemu_jqueryselect2_choice }
