pjm_app_homepage:
    path:     /
    defaults: { _controller: PJMAppBundle:App:index }

pjm_app_consos:
    resource: "@PJMAppBundle/Resources/config/Consos/routing.yml"
    prefix:   /consos

pjm_app_profil:
    resource: "@PJMAppBundle/Resources/config/Profil/routing.yml"
    prefix:   /profil

pjm_app_smoney:
    resource: "@PJMAppBundle/Resources/config/SMoney/routing.yml"
    prefix:   /smoney

pjm_app_admin:
    resource: "@PJMAppBundle/Resources/config/Admin/routing.yml"
    prefix:   /admin

pjm_app_a_propos:
    path:     /a-propos
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PJMAppBundle:App:a_propos.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400

pjm_app_contact:
    path:     /contact
    defaults: { _controller: PJMAppBundle:App:contact }

pjm_app_support_technique:
    path:     /support-technique
    defaults: { _controller: PJMAppBundle:App:supportTechnique }

pjm_app_plan_du_site:
    path:     /plan-du-site
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PJMAppBundle:App:en_construction.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
