pjm_app_homepage:
    path:     /
    defaults: { _controller: PJMAppBundle:App:index }

pjm_app_a_propos:
    path:     /a-propos
    defaults: { _controller: PJMAppBundle:App:aPropos }

pjm_app_contact:
    path:     /contact
    defaults: { _controller: PJMAppBundle:App:contact }

pjm_app_support_technique:
    path:     /support-technique
    defaults: { _controller: PJMAppBundle:App:supportTechnique }

pjm_app_plan_du_site:
    path:     /plan-du-site
    defaults: { _controller: PJMAppBundle:App:planDuSite }

pjm_app_consos:
    resource: "@PJMAppBundle/Resources/config/Consos/routing.yml"
    prefix:   /consos
