parameters:
    paiement.smoney.url: ***REMOVED***
    paiement.smoney.auth: Bearer ***REMOVED***

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
    pjm.twig.intranet_extension:
        class: PJM\AppBundle\Twig\IntranetExtension
        tags:
            - { name: twig.extension }
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager, @pjm.services.mailer]
    pjm.services.rezal:
        class:  PJM\AppBundle\Services\Rezal
        arguments: [@doctrine.orm.entity_manager, %kernel.environment%]
    pjm.services.mailer:
        class:  PJM\AppBundle\Services\Mailer
        arguments:
            - @mailer
            - @router
            - @twig
            - template:
                layout: 'PJMAppBundle:Mail:layout.html.twig'
                alerteSolde: 'PJMAppBundle:Mail:alerteSolde.html.twig'
              notificationEmail: "notification@physbook.fr"
              notificationSender: "Phy'sbook"
    pjm.listener.consos.historique:
        class: PJM\AppBundle\Listener\Consos\HistoriqueListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    pjm.listener.consos.transaction:
        class: PJM\AppBundle\Listener\Consos\TransactionListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    pjm.datatable.historique:
        class: PJM\AppBundle\Datatables\HistoriqueDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.vacances:
        class: PJM\AppBundle\Datatables\VacancesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.prix:
        class: PJM\AppBundle\Datatables\PrixDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.historiqueAdmin:
        class: PJM\AppBundle\Datatables\HistoriqueAdminDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.commandes:
        class: PJM\AppBundle\Datatables\CommandesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.credits:
        class: PJM\AppBundle\Datatables\CreditsDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.paniers.liste:
        class: PJM\AppBundle\Datatables\PaniersDatatable
        tags:
            - { name: sg.datatable.view }
