imports:
  - { resource: Boquette/services.yml }
  - { resource: voters.yml }
  - { resource: managers.yml }
  - { resource: twig.yml }
  - { resource: listeners.yml }
  - { resource: datatables.yml }
  - { resource: forms.yml }

services:
    doctrine_dbal_platform:
        class: Doctrine\DBAL\Platforms\MySqlPlatform
    pjm.services.linkParser:
        class: PJM\AppBundle\Services\LinkParser
    pjm.services.emoticonParser:
        class: PJM\AppBundle\Services\EmoticonParser
    pjm.services.payments.lydia:
        class: PJM\AppBundle\Services\Payments\LydiaProvider
        arguments: [@buzz, @pjm.services.transaction_manager, %paiement.lydia.url%, %paiement.lydia.auth%]
    pjm.services.image:
        class: PJM\AppBundle\Services\Image
        arguments: [@templating.helper.assets=]
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager, @pjm.services.mailer, @pjm.twig.intranet_extension, @pjm.services.rezal]
    pjm.services.group:
        class:  PJM\AppBundle\Services\Group
        arguments: [@doctrine.orm.entity_manager]
    pjm.services.trads:
        class:  PJM\AppBundle\Services\Trads
        arguments: [%exances%]
    pjm.services.random:
        class:  PJM\AppBundle\Services\Random
    pjm.services.rezal:
        class:  PJM\AppBundle\Services\Rezal
        arguments: [@doctrine.orm.entity_manager, %db_rezal_host%, %db_rezal_user%, %db_rezal_pass%]
    pjm.services.excel:
        class:  PJM\AppBundle\Services\Excel
        arguments: [@phpexcel, @logger]
    pjm.services.markdown:
        class:  PJM\AppBundle\Services\Markdown
    pjm.services.mailer:
        class:  PJM\AppBundle\Services\Mailer
        arguments:
            - @mailer
            - @router
            - @twig
            - template:
                layout: 'PJMAppBundle:Mail:layout.html.twig'
                alerteSolde: 'PJMAppBundle:Mail:alerteSolde.html.twig'
                message: 'PJMAppBundle:Mail:message.html.twig'
              notificationEmail: "notification@physbook.fr"
              contactEmail: "contact@physbook.fr"
              notificationSender: "Phy'sbook"
              errorEmail: "error@physbook.fr"
    pjm.services.push:
        class: PJM\AppBundle\Services\Push
        arguments: [@doctrine.orm.entity_manager, @minishlink_web_push]
    pjm.services.file_manager:
        class: PJM\AppBundle\Services\FileManager
        arguments: [%kernel.root_dir%]


