parameters:
    paiement.smoney.url: ***REMOVED***
    paiement.smoney.auth: Bearer ***REMOVED***

services:
    pjm.twig.intranet_extension:
        class: PJM\AppBundle\Twig\IntranetExtension
        tags:
            - { name: twig.extension }
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager]
