parameters:
    paiement.smoney.url: ***REMOVED***
    paiement.smoney.auth: Bearer ***REMOVED***
    paiement.smoney.url.dev: ***REMOVED***
    paiement.smoney.auth.dev: Bearer ***REMOVED***

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
    pjm.twig.intranet_extension:
        class: PJM\AppBundle\Twig\IntranetExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager, @pjm.services.mailer, @pjm.twig.intranet_extension]
    pjm.services.rezal:
        class:  PJM\AppBundle\Services\Rezal
        arguments: [@doctrine.orm.entity_manager, %kernel.environment%]
    pjm.services.mailer:
        class:  PJM\AppBundle\Services\Mailer
        arguments:
            - @mailer
            - @router
            - @twig
            - template:
                layout: 'PJMAppBundle:Mail:layout.html.twig'
                alerteSolde: 'PJMAppBundle:Mail:alerteSolde.html.twig'
                error: 'PJMAppBundle:Mail:error.html.twig'
              notificationEmail: "notification@physbook.fr"
              notificationSender: "Phy'sbook"
              errorEmail: "error@physbook.fr"
    pjm.listener.consos.historique:
        class: PJM\AppBundle\Listener\Consos\HistoriqueListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    pjm.listener.consos.transaction:
        class: PJM\AppBundle\Listener\Consos\TransactionListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }
    pjm.datatable.historique:
        class: PJM\AppBundle\Datatables\HistoriqueDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.vacances:
        class: PJM\AppBundle\Datatables\VacancesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.prix:
        class: PJM\AppBundle\Datatables\PrixDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.historiqueAdmin:
        class: PJM\AppBundle\Datatables\HistoriqueAdminDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.commandes:
        class: PJM\AppBundle\Datatables\CommandesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.credits:
        class: PJM\AppBundle\Datatables\CreditsDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.boquette.historique:
        class: PJM\AppBundle\Datatables\HistoriqueBoquetteDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.paniers.liste:
        class: PJM\AppBundle\Datatables\Admin\PaniersDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.responsabilites:
        class: PJM\AppBundle\Datatables\ResponsabilitesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.responsable:
        class: PJM\AppBundle\Datatables\ResponsableDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.boquette.item:
        class: PJM\AppBundle\Datatables\Boquette\ItemDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.featuredItem:
        class: PJM\AppBundle\Datatables\Admin\FeaturedItemDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.annuaire:
        class: PJM\AppBundle\Datatables\AnnuaireDatatable
        tags:
            - { name: sg.datatable.view }
