parameters:
    paiement.smoney.url: https://mon-espace-pp.s-money.fr/ecommerce/payments/smoney
    paiement.smoney.auth: Bearer MTsxMztUR3F4ZUZwdDFs

services:
    pjm.twig.intranet_extension:
        class: PJM\AppBundle\Twig\IntranetExtension
        tags:
            - { name: twig.extension }
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager]
