parameters:
    paiement.smoney.url: https://mon-espace-pp.s-money.fr/ecommerce/payments/smoney
    paiement.smoney.auth: Bearer MTsxMztUR3F4ZUZwdDFs


services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    pjm.twig.intranet_extension:
        class: PJM\AppBundle\Twig\IntranetExtension
        tags:
            - { name: twig.extension }
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager, @pjm.services.mailer]
    pjm.services.mailer:
        class:  PJM\AppBundle\Services\Mailer
        arguments:
            - @mailer
            - @router
            - @twig
            - template:
                layout: 'PJMAppBundle:Mail:layout.html.twig'
                alerteSolde: 'PJMAppBundle:Mail:alerteSolde.html.twig'
              notificationEmail: 'notification@physbook.fr'

