services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
    pjm.twig.intranet_extension:
        class: PJM\AppBundle\Twig\IntranetExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    pjm.services.utils:
        class:  PJM\AppBundle\Services\Utils
        arguments: [@doctrine.orm.entity_manager, @pjm.services.mailer, @pjm.twig.intranet_extension, @pjm.services.rezal]
    pjm.services.citation:
        class:  PJM\AppBundle\Services\Citation
        arguments: [@doctrine.orm.entity_manager, @templating]
    pjm.services.random:
        class:  PJM\AppBundle\Services\Random
    pjm.services.rezal:
        class:  PJM\AppBundle\Services\Rezal
        arguments: [@doctrine.orm.entity_manager, %kernel.environment%]
    pjm.services.excel:
        class:  PJM\AppBundle\Services\Excel
        arguments: [@phpexcel, @logger]
    pjm.services.mailer:
        class:  PJM\AppBundle\Services\Mailer
        arguments:
            - @mailer
            - @router
            - @twig
            - template:
                layout: 'PJMAppBundle:Mail:layout.html.twig'
                alerteSolde: 'PJMAppBundle:Mail:alerteSolde.html.twig'
                error: 'PJMAppBundle:Mail:error.html.twig'
              notificationEmail: "notification@physbook.fr"
              contactEmail: "contact@physbook.fr"
              notificationSender: "Phy'sbook"
              errorEmail: "error@physbook.fr"
    pjm.listener.consos.historique:
        class: PJM\AppBundle\Listener\Consos\HistoriqueListener
        tags:
            - { name: doctrine.event_subscriber }
    pjm.datatable.achats:
        class: PJM\AppBundle\Datatables\AchatsDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.transferts:
        class: PJM\AppBundle\Datatables\TransfertsDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.vacances:
        class: PJM\AppBundle\Datatables\VacancesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.prix:
        class: PJM\AppBundle\Datatables\PrixDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.commandes:
        class: PJM\AppBundle\Datatables\CommandesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.credits:
        class: PJM\AppBundle\Datatables\CreditsDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.boquette.historique:
        class: PJM\AppBundle\Datatables\HistoriqueBoquetteDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.paniers.liste:
        class: PJM\AppBundle\Datatables\Admin\PaniersDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.responsabilites:
        class: PJM\AppBundle\Datatables\ResponsabilitesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.boquettes:
        class: PJM\AppBundle\Datatables\Admin\BoquettesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.responsable:
        class: PJM\AppBundle\Datatables\ResponsableDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.consos.comptes:
        class: PJM\AppBundle\Datatables\Admin\ComptesDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.boquette.item:
        class: PJM\AppBundle\Datatables\Boquette\ItemDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.featuredItem:
        class: PJM\AppBundle\Datatables\Admin\FeaturedItemDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.admin.media.photos:
        class: PJM\AppBundle\Datatables\Admin\Media\PhotoDatatable
        tags:
            - { name: sg.datatable.view }
    pjm.datatable.annuaire:
        class: PJM\AppBundle\Datatables\AnnuaireDatatable
        tags:
            - { name: sg.datatable.view }
