parameters:
    paiement.smoney.auth: 'Bearer MTsxMztUR3F4ZUZwdDFs'
    paiement.smoney.url: 'https://mon-espace-pp.s-money.fr/ecommerce/payments/smoney'

services:
    pjm_app.rechargement:
        class: PJM\AppBundle\Rechargement\PJMRechargement
