services:
  security.access.boquette_voter:
    class: PJM\AppBundle\Security\BoquetteVoter
    arguments: [@pjm.services.responsable_manager]
    public: false
    tags:
      - { name: security.voter }
