pjm_app_consos_paniers_admin_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Paniers:admin }

pjm_app_consos_paniers_admin_listePaniers:
    path:     /listePaniers
    defaults: { _controller: PJMAppBundle:Consos/Paniers:listePaniers }

pjm_app_consos_paniers_admin_paniersResults:
    path:     /listePaniers/results
    defaults: { _controller: PJMAppBundle:Consos/Paniers:paniersResults }

pjm_app_consos_paniers_admin_listeCredits:
    path:     /listeCredits
    defaults: { _controller: PJMAppBundle:Consos/Paniers:listeCredits }

pjm_app_consos_paniers_admin_creditsResults:
    path:     /listeCredits/results
    defaults: { _controller: PJMAppBundle:Consos/Paniers:creditsResults }
