pjm_app_consos_paniers_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Paniers:index }

pjm_app_consos_paniers_commander:
    path:     /commander
    defaults: { _controller: PJMAppBundle:Consos/Paniers:commander }

pjm_app_consos_paniers_admin:
    resource: "@PJMAppBundle/Resources/config/Consos/Paniers/Admin/routing.yml"
    prefix:   /admin
