pjm_app_banque_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Banque:index }

pjm_app_banque_transfert:
    path:     /transfert
    defaults: { _controller: PJMAppBundle:Consos/Banque:transfert }

pjm_app_banque_transactionsResults:
    path:     /historique/transactions/{user}
    defaults: { _controller: PJMAppBundle:Consos/Banque:transactionsResults, user: null }

pjm_app_banque_achatsResults:
    path:     /historique/achats/{user}
    defaults: { _controller: PJMAppBundle:Consos/Banque:achatsResults, user: null }

pjm_app_banque_transfertsResults:
    path:     /historique/transferts/{user}
    defaults: { _controller: PJMAppBundle:Consos/Banque:transfertsResults, user: null }
