pjm_app_banque_index:
    path:     /
    methods: [ get ]
    defaults: { _controller: PJMAppBundle:Consos/Banque:index }

pjm_app_banque_transfert:
    path:     /transfert
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Consos/Banque:transfert }

pjm_app_banque_transactionsResults:
    path:     /historique/transactions
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Consos/Banque:transactionsResults }

pjm_app_banque_achatsResults:
    path:     /historique/achats
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Consos/Banque:achatsResults }

pjm_app_banque_transfertsResults:
    path:     /historique/transferts
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Consos/Banque:transfertsResults }
