pjm_app_admin_boquette_gestionItem:
    path:     /{slug}/gestionItem
    defaults: { _controller: PJMAppBundle:Consos/Boquette:gestionItem }

pjm_app_admin_boquette_gestionResponsables:
    path:     /{slug}/responsables
    defaults: { _controller: PJMAppBundle:Consos/Boquette:gestionResponsables }

pjm_app_admin_boquette_responsablesResults:
    path:     /{boquette_slug}/responsables/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:responsablesResults }

pjm_app_admin_boquette_gestionFeaturedItem:
    path:     /{slug}/featuredItem
    defaults: { _controller: PJMAppBundle:Consos/Boquette:gestionFeaturedItem }

pjm_app_admin_boquette_featuredItemResults:
    path:     /{boquette_slug}/featuredItem/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:featuredItemResults }

pjm_app_admin_boquette_modifierItem:
    path:     /{boquette}/item/{item}/modifier
    defaults: { _controller: PJMAppBundle:Consos/Boquette:modifierItem }
    options:
        expose: true

pjm_app_admin_boquette_gestionCredits:
    path:     /{slug}/gestionCredits
    defaults: { _controller: PJMAppBundle:Consos/Boquette:gestionCredits }

pjm_app_admin_boquette_creditsResults:
    path:     /{boquette_slug}/gestionCredits/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:creditsResults }

pjm_app_admin_boquette_exportCredits:
    path:     /{slug}/exportCredits
    defaults: { _controller: PJMAppBundle:Consos/Boquette:exportCredits }

pjm_app_admin_boquette_voirComptes:
    path:     /{slug}/comptes
    defaults: { _controller: PJMAppBundle:Consos/Boquette:voirComptes }

pjm_app_admin_boquette_comptesResults:
    path:     /{boquette_slug}/comptes/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:comptesResults }

pjm_app_admin_boquette_pians:
    resource: "@PJMAppBundle/Resources/config/Admin/Boquette/Pians/routing.yml"
    prefix:   /pians

pjm_app_admin_boquette_brags:
    resource: "@PJMAppBundle/Resources/config/Admin/Boquette/Brags/routing.yml"
    prefix:   /brags

pjm_app_admin_boquette_paniers:
    resource: "@PJMAppBundle/Resources/config/Admin/Boquette/Paniers/routing.yml"
    prefix:   /paniers

pjm_app_admin_boquette_cvis:
    resource: "@PJMAppBundle/Resources/config/Admin/Boquette/Cvis/routing.yml"
    prefix:   /cvis

pjm_app_admin_boquette_asso:
    resource: "@PJMAppBundle/Resources/config/Admin/Boquette/Asso/routing.yml"
    prefix:   /asso

pjm_app_admin_boquette_default:
    path:     /{slug}
    defaults: { _controller: PJMAppBundle:Consos/Boquette:defaultAdmin }
