pjm_app_consos_pians_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Pians:index }

pjm_app_consos_pians_boissonDuMois:
    path:     /boissonDuMois
    defaults: { _controller: PJMAppBundle:Consos/Pians:boissonDuMois }

