pjm_app_homepage:
    path:     /
    defaults: { _controller: PJMAppBundle:Accueil:index }

pjm_app_accueil_etatComptes:
    path:     /etatComptes
    defaults: { _controller: PJMAppBundle:Accueil:etatComptes }

pjm_app_accueil_anniversaires:
    path:     /anniversaires
    defaults: { _controller: PJMAppBundle:Accueil:anniversaires }
