pjm_app_notifications_index:
    path:     /
    methods: [ get ]
    defaults: { _controller: PJMAppBundle:Notifications:index }

pjm_app_notifications_reglages:
    path:     /reglages
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Notifications:reglages }

pjm_app_notifications_last:
    path:     /last
    methods: [ get ]
    defaults: { _controller: PJMAppBundle:Notifications:last }
