pjm_app_boquette_brags_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Brags:index }

pjm_app_boquette_brags_commande:
    path:     /commande
    defaults: { _controller: PJMAppBundle:Consos/Brags:commande }
