<?php

namespace PJM\AppBundle\Entity;

use PJM\UserBundle\Entity\User;

/**
 * PushSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function callbackFindByUser(User $user)
    {
        return function($qb) use($user) {
            $qb
                ->join('PushSubscription.user', 'u', 'WITH', 'u = :user')
                ->setParameter('user', $user)
            ;
        };
    }
}
