<?php

namespace PJM\AppBundle\Entity;

/**
 * PushSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
