pjm_app_inbox_index:
    path:     /
    methods: [ get ]
    defaults: { _controller: PJMAppBundle:Inbox:index }

pjm_app_inbox_nouveauMessage:
    path:     /nouveau-message/{user}
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Inbox:nouveau, user: null, annonce: false }
    options:
        expose: true

pjm_app_inbox_nouvelleAnnonce:
    path:     /nouvelle-annonce/{user}
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Inbox:nouveau, user: null, annonce: true }

pjm_app_inbox_lu:
    path:     /lu/{reception}
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Inbox:lu }
    options:
        expose: true

pjm_app_inbox_supprimer:
    path:     /supprimer/{reception}
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Inbox:supprimer }
    options:
        expose: true

pjm_app_inbox_annuler:
    path:     /annuler/{message}
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Inbox:annuler }
    options:
        expose: true
