pjm_app_inbox_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Inbox:index }

pjm_app_inbox_nouveauMessage:
    path:     /nouveau-message/{user}
    defaults: { _controller: PJMAppBundle:Inbox:nouveau, user: null, annonce: false }

pjm_app_inbox_nouvelleAnnonce:
    path:     /nouvelle-annonce/{user}
    defaults: { _controller: PJMAppBundle:Inbox:nouveau, user: null, annonce: true }


pjm_app_inbox_lu:
    path:     /lu/{reception}
    defaults: { _controller: PJMAppBundle:Inbox:lu }
    requirements:
        _method: POST
    options:
        expose: true

pjm_app_inbox_supprimer:
    path:     /supprimer/{reception}
    defaults: { _controller: PJMAppBundle:Inbox:supprimer }
    requirements:
        _method: POST
    options:
        expose: true

pjm_app_inbox_annuler:
    path:     /annuler/{message}
    defaults: { _controller: PJMAppBundle:Inbox:annuler }
    requirements:
        _method: POST
    options:
        expose: true
