pjm_profil_modifier:
    path:       /modifier
    defaults:   { _controller: PJMAppBundle:Profil:modifier }

pjm_profil_annuaire:
    path:       /annuaire
    defaults:   { _controller: PJMAppBundle:Profil:annuaire }

pjm_profil_annuaireResults:
    path:       /annuaire/results
    defaults: { _controller: PJMAppBundle:Profil:annuaireResults }

fos_user_profile_show:
    path:       /
    defaults:   { _controller: PJMAppBundle:Profil:voir }

pjm_profil_voir:
    path:       /voir/{username}
    defaults:   { _controller: PJMAppBundle:Profil:voir }

pjm_profil_encart:
    path:       /encart/{username}/{content}
    defaults:   { _controller: PJMAppBundle:Profil:encart, content: false }
    options:
        expose: true
