pjm_news_accueil:
    path:     /{page}
    defaults: { _controller: PJMNewsBundle:News:index, page: 1 }
    requirements:
        page:  \d*

pjm_news_extrait:
    path:     /extrait/{nombre}
    defaults: { _controller: PJMNewsBundle:News:menu, nombre: 3 }
    requirements:
        nombre:  \d*

pjm_news_voir:
    path:      /article/{slug}
    defaults:  { _controller: PJMNewsBundle:News:voir }

pjm_news_ajouter:
    path:      /ajouter
    defaults:  { _controller: PJMNewsBundle:News:ajouter }

pjm_news_modifier:
    path:      /modifier/{slug}
    defaults:  { _controller: PJMNewsBundle:News:modifier }

pjm_news_supprimer:
    path:      /supprimer/{slug}
    defaults:  { _controller: PJMNewsBundle:News:supprimer }
