parameters:
#    pjm_news.example.class: PJM\NewsBundle\Example

services:
    pjm_news.antispam:
        class: PJM\NewsBundle\Antispam\PJMAntispam
        arguments: [@mailer, %locale%, 3]
    pjm_news.validator.antiflood:
            class: PJM\NewsBundle\Validator\AntifloodValidator
            arguments: [@request, @doctrine.orm.entity_manager]
            scope: request
            tags:
                - { name: validator.constraint_validator, alias: pjm_news_antiflood }
