pjm_app_smoney_rechargement_getURL:
    path:     /envoi/{transaction}
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:getURL }

pjm_app_boquette_rechargement_confirm:
    path:     /{slug}/rechargement/confirm
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement:confirm }

pjm_app_boquette_rechargement_cancel:
    path:     /{slug}/rechargement/cancel
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement:cancel }

pjm_app_boquette_rechargement_expire:
    path:     /{slug}/rechargement/expire
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement:expire }

pjm_app_boquette_rechargement_success:
    path:     /{slug}/rechargement/success
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement:success }

pjm_app_boquette_rechargement_fail:
    path:     /{slug}/rechargement/fail
    methods: [ post ]
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement:fail }

pjm_app_smoney_rechargement_retourSMoney:
    path:     /retour
    methods: [ get, post ]
    defaults:
        _controller: PJMAppBundle:Consos/Rechargement:retourSMoney

pjm_app_smoney_rechargement_redirectionDepuisSMoney:
    path:     /redirection
    methods: [ get, post ]
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:redirectionDepuisSMoney }