pjm_app_smoney_rechargement_getURL:
    path:     /envoi/{montant}/{boquette_slug}
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:getURL }
    requirements:
        _method: POST

pjm_app_smoney_rechargement_retourSMoney:
    path:     /retour
    defaults:
        _controller: PJMAppBundle:Consos/Rechargement:retourSMoney

pjm_app_smoney_rechargement_redirectionDepuisSMoney:
    path:     /redirection
    defaults: { _controller: PJMAppBundle:Consos/Rechargement:redirectionDepuisSMoney }
