pjm_app_boquette_listeItem:
    path:     /{slug}/item
    defaults: { _controller: PJMAppBundle:Consos/Boquette:listeItem }

pjm_app_boquette_itemResults:
    path:     /{boquette_slug}/item/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:itemResults }
