pjm_app_boquette_listeItem:
    path:     /{slug}/listeItem
    defaults: { _controller: PJMAppBundle:Consos/Boquette:listeItem }

pjm_app_boquette_itemResults:
    path:     /{boquette_slug}/item/results
    defaults: { _controller: PJMAppBundle:Consos/Boquette:itemResults }

pjm_app_boquette_getItems:
    path:     /{boquette_slug}/item/liste/{offset}
    defaults: { _controller: PJMAppBundle:Consos/Boquette:getItems }
    options:
        expose: true

pjm_app_boquette_historique:
    path:     /historique
    defaults: { _controller: PJMAppBundle:Consos:historique }

pjm_app_boquette_historiqueResults:
    path:     /historique/results
    defaults: { _controller: PJMAppBundle:Consos:historiqueResults }

pjm_app_boquette_voirResponsables:
    path:     /{slug}/responsables
    defaults: { _controller: PJMAppBundle:Consos/Boquette:voirResponsables }

pjm_app_boquette_boquette_historique:
    path:     /{slug}/historique
    defaults: { _controller: PJMAppBundle:Consos/Boquette:historique }

pjm_app_boquette_rechargement:
    path:     /{slug}/rechargement
    defaults: { _controller: PJMAppBundle:Consos/Boquette:rechargement }

pjm_app_boquette_itemHM:
    path:     /hm/{item}
    defaults: { _controller: PJMAppBundle:Consos/Boquette:itemHM }

pjm_app_boquette_pians:
    resource: "@PJMAppBundle/Resources/config/Boquette/Pians/routing.yml"
    prefix:   /pians

pjm_app_boquette_cvis:
    resource: "@PJMAppBundle/Resources/config/Boquette/Cvis/routing.yml"
    prefix:   /cvis

pjm_app_boquette_brags:
    resource: "@PJMAppBundle/Resources/config/Boquette/Brags/routing.yml"
    prefix:   /brags

pjm_app_boquette_paniers:
    resource: "@PJMAppBundle/Resources/config/Boquette/Paniers/routing.yml"
    prefix:   /paniers

pjm_app_boquette_uai:
    resource: "@PJMAppBundle/Resources/config/Boquette/UAI/routing.yml"
    prefix:   /uai

pjm_app_boquette_tuiss:
    resource: "@PJMAppBundle/Resources/config/Boquette/Tuiss/routing.yml"
    prefix:   /tuiss

pjm_app_boquette_asso:
    resource: "@PJMAppBundle/Resources/config/Boquette/Asso/routing.yml"
    prefix:   /asso
