services:
    pjm.services.boquette:
        class:  PJM\AppBundle\Services\Boquette\BoquetteService
        arguments: [@doctrine.orm.entity_manager]
    pjm.services.boquette.brags:
        class:  PJM\AppBundle\Services\Boquette\BragsService
        arguments: [%special_boquettes%]
        parent: pjm.services.boquette
    pjm.services.boquette.paniers:
        class:  PJM\AppBundle\Services\Boquette\PaniersService
        arguments: [%special_boquettes%]
        parent: pjm.services.boquette
    pjm.services.boquette.cvis:
        class:  PJM\AppBundle\Services\Boquette\CvisService
        arguments: [%special_boquettes%]
        parent: pjm.services.boquette
    pjm.services.boquette.pians:
        class:  PJM\AppBundle\Services\Boquette\PiansService
        arguments: [%special_boquettes%]
        parent: pjm.services.boquette
