pjm_app_admin_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Admin:index }

pjm_app_admin_users_liste:
    path:     /users/liste
    defaults: { _controller: PJMAppBundle:Admin:liste }

pjm_app_admin_users_inscriptionListe:
    path:     /users/inscription/liste
    defaults: { _controller: PJMAppBundle:Admin:inscriptionListe }

pjm_app_admin_users_inscriptionUnique:
    path:     /users/inscription/unique
    defaults: { _controller: PJMAppBundle:Admin:inscriptionUnique }

pjm_app_admin_responsabilitesResults:
    path:     /responsabilites/results
    defaults: { _controller: PJMAppBundle:Admin:responsabilitesResults }

pjm_app_admin_responsabilites:
    path:     /responsabilites/{responsabilite}
    defaults: { _controller: PJMAppBundle:Admin:responsabilites, responsabilite: null }
    options:
        expose: true

pjm_app_admin_toggleResponsables:
    path:     /responsables/toggle
    defaults: { _controller: PJMAppBundle:Consos/Boquette:toggleResponsables }

pjm_app_admin_gestionBoquettes:
    path:     /gestionBoquettes/{boquette}
    defaults: { _controller: PJMAppBundle:Admin:gestionBoquettes, boquette: null }

pjm_app_admin_boquette:
    resource: "@PJMAppBundle/Resources/config/Admin/Boquette/routing.yml"
    prefix:   /boquette
