<?php

namespace PJM\AppBundle\Entity\Event;

use Doctrine\ORM\EntityRepository;
use PJM\UserBundle\Entity\User;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
    public function getEvents(User $user, $max = 6, $quand = 'after', \DateTime $date = null, Evenement $eventExclure = null)
    {
        if ($date == null) {
            $date = new \DateTime();
        }

        $qb = $this->createQueryBuilder('e')
            ->where('e.isPublic = true')
            ->leftJoin('e.invitations', 'i')
            ->orWhere('e.isPublic = false AND i.invite = :user')
            ->setParameter('user', $user)
        ;

        if ($eventExclure !== null) {
            $qb
                ->andWhere('e != :eventExclure')
                ->setParameter('eventExclure', $eventExclure)
            ;
        }

        if ($quand == 'after') {
            $qb
                ->andWhere('e.dateDebut > :date')
                ->orderBy('e.dateDebut', 'ASC')
            ;
        } else if ($quand == 'before') {
            $qb
                ->andWhere('e.dateDebut <= :date')
                ->orderBy('e.dateDebut', 'DESC')
            ;
        }

        $qb->setParameter('date', $date);

        if ($max !== null) {
            $qb
                ->setMaxResults($max)
            ;
        }

        $res = $qb->getQuery()->getResult();

        if ($quand == 'before') {
            $res = array_reverse($res);
        }

        return $res;
    }
}
