<?php

namespace PJM\AppBundle\Entity\Event;

/**
 * InvitationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
