pjm_app_consos_brags_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Brags:index }

pjm_app_consos_brags_commande:
    path:     /commande
    defaults: { _controller: PJMAppBundle:Consos/Brags:commande }

pjm_app_consos_brags_rechargement:
    path:     /rechargement
    defaults: { _controller: PJMAppBundle:Consos/Brags:rechargement }

pjm_app_consos_brags_admin:
    resource: "@PJMAppBundle/Resources/config/Consos/Brags/Admin/routing.yml"
    prefix:   /admin
