pjm_app_consos_brags_index:
    path:     /
    defaults: { _controller: PJMAppBundle:Consos/Brags:index }

pjm_app_consos_brags_commande:
    path:     /commande
    defaults: { _controller: PJMAppBundle:Consos/Brags:commande }
    requirements:
        _method: POST
